name: Deploy on AKS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: The name of the environment where to deploy
        type: string
      branch:
        required: false
        default: ${{ github.ref_name }}
        type: string
    secrets:
      CLIENT_ID:
        required: true
      SUBSCRIPTION_ID:
        required: true
      TENANT_ID:
        required: true

env:
  APP_NAME: pagopaqijsmmanagementfunction

jobs:
  deploy:
    runs-on: [ self-hosted-job, "${{ inputs.environment }}" ]
    name: Deploy on AKS
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Deploy
        uses: pagopa/github-actions-template/aks-deploy@713f5abd8f8ee210e5f6a4243ae52eb7c1b3b5ab # v2.4.1
        with:
          branch: ${{ inputs.branch }}
          client_id: ${{ secrets.CLIENT_ID }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          env: ${{ inputs.environment }}
          namespace: ${{ vars.NAMESPACE }}
          cluster_name: ${{ vars.CLUSTER_NAME }}
          resource_group: ${{ vars.CLUSTER_RESOURCE_GROUP }}
          app_name: ${{ env.APP_NAME }}
          helm_upgrade_options: "--debug --set microservice-chart.azure.workloadIdentityClientId=${{vars.WORKLOAD_IDENTITY_ID}}"
          timeout: '5m0s'
